// <auto-generated />
using System;
using CentralDoSaber.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CentralDoSaber.Infrastructure.Migrations
{
    [DbContext(typeof(CentralDoSaberContext))]
    partial class CentralDoSaberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("TB_AUTORES", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ConteudoId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ConteudoId");

                    b.HasIndex("UserId", "ConteudoId")
                        .IsUnique();

                    b.ToTable("TB_AVALIACOES", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ConteudoId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ConteudoId");

                    b.HasIndex("UserId");

                    b.ToTable("TB_COMENTARIOS", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Conteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DataLancamento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<Guid>("EditoraId")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("NumeroCapitulos")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NumeroPaginas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("EditoraId");

                    b.ToTable("TB_CONTEUDOS", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.ConteudoGenero", b =>
                {
                    b.Property<Guid>("ConteudoId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("GeneroId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("ConteudoId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("TB_CONTEUDO_GENEROS", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Editora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_EDITORAS", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("TB_GENEROS", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TB_USERS", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.UserConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("NotificacoesAtivas")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TB_USER_CONFIGURATIONS", (string)null);
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("CentralDoSaber.Domain.Entities.Conteudo", "Conteudo")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralDoSaber.Domain.Entities.User", "User")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteudo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("CentralDoSaber.Domain.Entities.Conteudo", "Conteudo")
                        .WithMany("Comentarios")
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralDoSaber.Domain.Entities.User", "User")
                        .WithMany("Comentarios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteudo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Conteudo", b =>
                {
                    b.HasOne("CentralDoSaber.Domain.Entities.Autor", "Autor")
                        .WithMany("Conteudos")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralDoSaber.Domain.Entities.Editora", "Editora")
                        .WithMany("Conteudos")
                        .HasForeignKey("EditoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Editora");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.ConteudoGenero", b =>
                {
                    b.HasOne("CentralDoSaber.Domain.Entities.Conteudo", "Conteudo")
                        .WithMany("ConteudoGeneros")
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralDoSaber.Domain.Entities.Genero", "Genero")
                        .WithMany("ConteudoGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteudo");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.UserConfiguration", b =>
                {
                    b.HasOne("CentralDoSaber.Domain.Entities.User", null)
                        .WithOne("Configuration")
                        .HasForeignKey("CentralDoSaber.Domain.Entities.UserConfiguration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Autor", b =>
                {
                    b.Navigation("Conteudos");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Conteudo", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Comentarios");

                    b.Navigation("ConteudoGeneros");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Editora", b =>
                {
                    b.Navigation("Conteudos");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.Genero", b =>
                {
                    b.Navigation("ConteudoGeneros");
                });

            modelBuilder.Entity("CentralDoSaber.Domain.Entities.User", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Comentarios");

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
